name: Create releases
on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'anthropics/anthropic-cli'
    runs-on: ubuntu-latest
    environment: production-release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - uses: stainless-api/trigger-release-please@v1
        id: release
        with:
          repo: ${{ github.event.repository.full_name }}
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}
