name: Dagger CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: "latest"
          call: lint
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: "latest"
          call: test
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build All
        uses: dagger/dagger-for-github@v8.4.0
        with:
          version: "latest"
          call: build-all
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
